version: '3.8'

services:
  app:
    build: ./app
    env_file: 
      - .env  # Для секретных переменных
    volumes:
      - ./app:/app
    depends_on:
      - database
      # - rabbitmq

  web-proxy:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app
  
  # rabbitmq:
  #   image: rabbitmq:management
  #   ports:
  #     - "15672:15672"
  #     - "5672:5672"
  #   volumes:
  #     - rabbitmq_data:/var/lib/rabbitmq
  #   environment:
  #     RABBITMQ_DEFAULT_USER: "user"
  #     RABBITMQ_DEFAULT_PASS: "user"
  #   restart: on-failure

  database:
    image: postgres:15
    env_file: .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped


volumes:
  postgres_data:
    driver: local
  # rabbitmq_data:
  #   driver: local