version: '3.8'

services:
  app:
    build: ./app
    env_file: 
      - .env  # Для секретных переменных
    environment:
      - APP_CONFIG_PATH=/app/config/settings.yaml  # Путь к YAML-конфигу
    volumes:
      - ./app:/app
      - ./app/config:/app/config  # Монтируем папку с конфигами
    depends_on:
      - database
      - rabbitmq

  web-proxy:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app
  
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER:-user}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    restart: on-failure

  database:
    image: postgres:15
    env_file: .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-myapp}
      POSTGRES_USER: ${POSTGRES_USER:-user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped


volumes:
  postgres_data:
    driver: local
  rabbitmq_data:
    driver: local